seata:
  enabled: true #开启seata分布式事务
  application-id: ${spring.application.name} #client 服务名称
  tx-service-group: seata-server-group #该名称必须和 service.vgroup-mapping 下相同
  enable-auto-data-source-proxy: false #关闭数据源自动代理，框架已经集成，包括多数据源
  service:
    vgroup-mapping:
      seata-server-group: seata-server #服务发现组件上的 seata-server 服务名
  registry:
    type: redis
    redis:
      serverAddr: ${spring.redis.host}:${spring.redis.port:6379}
      cluster: seata-server
      db: ${spring.redis.database}
      timeout: ${spring.redis.timeout}
