payconfig:
  wechatpay:
    appId: wx7650561dc89e59af  #服务号appID
    mchId: 1452903402           #商户id
    signType: MD5
    secretKey: ef3dddc832ee41c1ff9346178d07bb96
    apiDomain: https://api.mch.weixin.qq.com
    notifyUrl: http://192.168.20.5:8940/yysc/tp/trade/notify
    returnUrl: /marketplace-web/marketplace/paysSccess
    certPath: certs/apiclient_cert.p12   # 包含了私钥信息的证书文件，退款接口时必须

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://192.168.20.5:2105/eureka/ # 指向配置eureka地址
wbfc:
  swaggerui:
    enable: true
    title: 应用市场-交易服务(买家买家操作流程、支付功能) #标题

logging: # 日志输出配置
  level:
    com.wisea: DEBUG
    org.quartz: debug
